### ISSUE TITLE
Recipes to migrate from jss to jamf [editable list]

### ISSUE THREAD

**Issue by grahampugh** [eth-its/autopkg-mac-recipes-yaml#9]
This is a catch all list of existing jss recipes that should be migrated to jamf recipes as time allows.

- [x] Adobe Acrobat Reader DC - #51 
- [x] Adobe CC Apps for SDL (Acrobat DC, After Effects CC, Illustrator CC, InDesign CC, Lightroom Classic CC, Photoshop CC, Premiere Pro CC)
- [x] Adobe CC Cleaner
- [x] Adobe CC Serializer
- [x] Adobe Creative Cloud (Desktop app), plus SDL version
- ~Adobe SDL License Remover~ - can't remember why we need this
- [x] Affinity Designer
- [x] Affinity Photo
- [x] Affinity Publisher
- [x] Affinity License
- [x] Atom
- [x] BBEdit - #10 
- [x] ChemDraw 21+
- [x] Citrix Workspace - #52 
- [x] COMSOL Multiphysics
- [x] DataWarrior
- [x] DjView
- [x] Dropbox - #17 
- [x] Enpass
- [x] ETH Printer Drivers - #53 
- [x] Fiji
- ~FileVault Enforce at Login~ (or switch to a profile solution)
- [x] Final Cut Pro - #54 
- [x] GIMP
- [x] GraphicConverter 12+
- [x] IBM Spectrum Protect
- [x] ISL Light Client - #11 
- [x] iTerm
- [x] Jamf Pro Suite - deprecated 
- [x] JMP - #32 
- [x] KeePassX - deprecated
- [x] LibreOffice
- [x] Logic Pro X - #54 
- [x] Logitech Presentation
- [x] MacTeX
- [x] Maple 2022+
- [x] Mattermost
- [x] MATLAB R2021a+
- [x] MAXQDA 2021+
- [x] MestReNova
- [x] Microsoft Office 2019+
- [x] Microsoft Office 365
- [x] MindManager
- [x] Motion - #54 
- ~NoMAD~ - deprecated
- ~NoMAD Login AD~ - deprecated
- [x] Parallels Desktop - #22 
- [x] polybox
- [x] PopChar
- [x] Prism
- [x] Privileges
- [x] PyMOL
- [x] Quicksilver
- [x] R
- [x] RStudio
- [x] SeqMonk
- [x] Skim
- ~Skype for Business~ - deprecated
- ~Sophos Anti-Virus~ - deprecated
- ~Sophos Anti-Virus EC~ - deprecated
- [x] texmaker
- [x] TeXShop
- [x] ThinLinc Client
- [x] Thunderbird (EN/DE) - #20 
- [x] Unison
- [x] VLC
- [x] VMware Horizon Client
- [x] XQuartz
- [x] Zoom Client - #41

**Comment by grahampugh** [comment]
BBEdit +1 priority due to an icon change.
